name: breezvideo
description: Video test for breez.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.7.1
  flutter_playout: ^2.0.1
  path: ^1.8.0
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
